[13.0][l10n_do_pos] complete pos location
odoo-dominicana/l10n-dominicana pull request #762
Opened 2021-01-28 05:35 UTC by raulovallet

2021-02-05 14:05 UTC, jlopezg requested changes
Ver comentarios

2021-02-05 14:05 UTC, jlopezg commented on l10n_do_pos/models/ir_sequence.py
> +    def get_expiration_date_and_next_by_id(self):
Vamos a renombrar esta función por: `get_l10n_do_fiscal_info`

2021-02-05 14:05 UTC, jlopezg commented on l10n_do_pos/models/pos_config.py
> +    def get_extra_fiscal_info(self):
`get_l10n_do_fiscal_type_data`

2021-03-04 13:19 UTC, jlopezg approved these changes

2021-03-04 13:19 UTC, jlopezg commented
@andrp92 vamos a darle amora este PR

2021-05-14 05:25 UTC, akevinieron commented on l10n_do_pos/models/pos_config.py
>      # TODO: search criteria
Creo que se puede eliminar esto! No vi un caso de la vida real donde se use esta configuración!

La posibilidad de buscar por todos estos criterios por defecto si está bien. Lo que no veo necesaria es tener una configuración que permita colocar los criterios de busqueda.

2021-05-18 01:17 UTC, raulovallet commented on l10n_do_pos/models/pos_config.py
>      # TODO: search criteria
@jlopezg para que colocaste esto?

2021-06-02 23:17 UTC, andrp92 commented on l10n_do_pos/models/pos_config.py
>      # TODO: search criteria
@jlopezg en el punto de venta no necesitaríamos esto, o sí ? salvo sea un cliente que multi-country que haya que tener un POS fuera de RD con comportamiento nativo. 

cc: @raulovallet @akevinieron

2021-06-04 15:03 UTC, akevinieron approved these changes

2021-06-04 15:04 UTC, merged