[FIX] l10n_do_accounting: fix translated term
odoo-dominicana/l10n-dominicana pull request #768
Opened 2021-02-01 21:16 UTC by jlopezg

2021-02-01 22:07 UTC, mamcode approved these changes

2021-02-02 01:18 UTC, andrp92 approved these changes, later dismissed

2021-02-02 01:25 UTC, andrp92 commented on l10n_do_accounting/i18n/es_DO.po
> +msgid "Document number %s doesn't fit with the expected structure"
Sugerencia de términos: 

The structure of Document number is invalid.
La estructura del Número de Documento es invalida.

2021-02-02 01:25 UTC, andrp92 requested changes, later dismissed
Review comments

2021-02-08 14:43 UTC, merged