[IMP] l10n_do_accounting: implemented ncf_expiration_date by sequence
odoo-dominicana/l10n-dominicana pull request #770
Opened 2021-02-03 17:01 UTC by jlopezg

- Remove NCF Expiration date from company
- Add NCF Expiration date to sequence
- Write NCF Expiration date on invoice on post
- Get Invoice Template NCF Expiration date from invoice itself
- Y ya 🤔

2021-02-04 04:43 UTC, andrp92 approved these changes

2021-02-05 03:17 UTC, raulovallet commented
@jlopezg creo que es mejor ponerle el prefijo l10n_do_ncf_expiration_date????

2021-02-05 14:17 UTC, jlopezg commented
> @jlopezg creo que es mejor ponerle el prefijo l10n_do_ncf_expiration_date????

@raulovallet al menos ese se mantendrá así en 13.0 para mantener la compatibilidad con otro módulo que conocemos. En 14.0 me aseguro de ponerle el prefijo. 😎

2021-02-05 14:19 UTC, gustavovalverde requested changes
Si se va a remover l10n_do_ncf_exp_date  hay que hacer un script de migración para remover esta información de la DB, y aumentar la versión en el manifest.

2021-02-05 15:54 UTC, jlopezg commented
> Si se va a remover l10n_do_ncf_exp_date hay que hacer un script de migración para remover esta información de la DB, y aumentar la versión en el manifest.

Ese "remover esta información de la DB" no sucede automáticamente cuando haces update al módulo?

2021-02-08 14:42 UTC, andrp92 commented
> > Si se va a remover l10n_do_ncf_exp_date hay que hacer un script de migración para remover esta información de la DB, y aumentar la versión en el manifest.
> 
> Ese "remover esta información de la DB" no sucede automáticamente cuando haces update al módulo?

Yo tengo entendido que sí, Odoo hace clean up en las tablas. @gustavovalverde estás seguro que es necesario?

2021-02-09 15:05 UTC, andrp92 approved these changes

2021-02-09 15:06 UTC, merged