[13.0][l10n_do_pos] sales journal management.
odoo-dominicana/l10n-dominicana pull request #817
Opened 2021-06-13 23:06 UTC by raulovallet

Block open and close pos session if sales journal is fiscal,

2021-06-13 23:18 UTC, andrp92 requested changes

2021-06-13 23:18 UTC, andrp92 commented on l10n_do_pos/models/pos_config.py
> +            raise ValidationError(_("The Sales Journal cannot be fiscal! Please change the settings at the point of "
Agregar traducción

2021-06-13 23:18 UTC, andrp92 commented on l10n_do_pos/models/pos_session.py
> +    def action_pos_session_close(self):
¿Por qué hacemos la revisión al momento de cerrarlo, y no al momento de abrirlo? Yo entiendo que debe ser cuando se guarde la configuración o en su defecto, cuando se vaya a abrir la sesión. Sabemos las implicaciones de que esa información esté mal y que suba la sesión. El pos.config "no se puede" modificar mientras está abierta la sesión.

2021-06-13 23:19 UTC, akevinieron reviewed
Está genial @raulovallet.

Sin embargo, se me acaba de ocurrir un escenario (medio edge, pero posible). Se pudiera colocar un diario NO fiscal en la configuración del diario de venta en el POS, luego (otro día) a alguien se le ocurre ir a la configuración en contabilidad y volver ese diario fiscal.

Qué opinas? Sería buena idea validar tambien de ese lado?

2021-06-13 23:26 UTC, raulovallet commented on l10n_do_pos/models/pos_session.py
> +    def action_pos_session_close(self):
_check_company_journal se llama al abrir las session (odoo nativo), al modificar el diario (odoo nativo) y al cerrar la session (custom).

2021-06-13 23:28 UTC, raulovallet commented
> Está genial @raulovallet.
> 
> Sin embargo, se me acaba de ocurrir un escenario (medio edge, pero posible). Se pudiera colocar un diario NO fiscal en la configuración del diario de venta en el POS, luego (otro día) a alguien se le ocurre ir a la configuración en contabilidad y volver ese diario fiscal.
> 
> Qué opinas? Sería buena idea validar tambien de ese lado?

Si esta contenplado, por eso llama a confimar que el diario sea no fiscal, al abrir o cerrar el pos.

2021-06-14 12:15 UTC, jlopezg commented
@raulovallet @akevinieron debería un POS fiscal que haya emitido pedidos/facturas fiscales poder cambiar su diario de facturación por otro NO fiscal?

La localización Latam base (l10n_latam_invoice_document) tiene un constraint para esto a nivel de diarios de ventas/compras.

2021-06-14 12:46 UTC, akevinieron commented
@jlopezg estoy de acuerdo con que haya un constraint.

No creo que haya un gran problema con hacer este cambio porque creo que ese diario se usa unicamente al momento preciso de crear la orden para crear inmediatamente una factura y no se utiliza para más nada. 

Pero igual no tiene sentido un cambio como este en medio de una session de POS. Funcionalmente no se me ocurre un caso de uso donde eso pueda tener sentido. Y como no es una acción esperada ni lógica y pudiera causar algunos conflictos inesperados por esas razones estoy de acuerdo con que haya un constraint.

2021-06-14 12:49 UTC, jlopezg commented
> @jlopezg estoy de acuerdo con que haya un constraint.
> 
> No creo que haya un gran problema con hacer este cambio porque creo que ese diario se usa unicamente al momento preciso de crear la orden para crear inmediatamente una factura y no se utiliza para más nada.
> 
> Pero igual no tiene sentido un cambio como este en medio de una session de POS. Funcionalmente no se me ocurre un caso de uso donde eso pueda tener sentido. Y como no es una acción esperada ni lógica y pudiera causar algunos conflictos inesperados por esas razones estoy de acuerdo con que haya un constraint.

@raulovallet con el contexto de lo que dice @akevinieron , mira esto:
https://github.com/odoo/odoo/blob/30f62dcb19407cd7e9c039407b4ea8177cd41ca4/addons/l10n_latam_invoice_document/models/account_journal.py#L29

2021-06-14 14:18 UTC, raulovallet commented
> @raulovallet con el contexto de lo que dice @akevinieron , mira esto:

Lo que pasa es que el modulo latam por sí solo tiene sus choques con el punto de venta, no hay forma de evitar que el punto de venta haga sus asientos contables. Como la factura y los asientos contables son lo mismo, cuando intenta de hacer el asiento contable para este tipo de diarios es obligatorio tener el tipo de documento.

Creo que lo importante aquí es que no le salga un error a "lo loco" al usuario y que simplemente le diga que tiene que hacer, lo que he visto en los reportes es que para el diario de ventas y para el diario de factura le ponen el mismo diario y realmente deben ser dos diferentes (como ya viene pre-configurado cuando instalas el punto de venta).

La única forma de que veo que se le "tranque el juego" es si el usuario abre la caja, cambia el diario a fiscal (con la caja abierta), crea una factura con ese diario y después quiere cerrar la caja, al cerrar la caja te va a decir el mensaje que ya establecimos, si intentas de cambiar el diario no te deja porque la caja esta abierta y si intenta de cambiarlo a no fiscal no te va a dejar porque ya existe una factura fiscal... lo que debe hacer en este caso es cancelar todas las facturas de ese diario y pasar el diario a no fiscal...

2021-06-14 17:27 UTC, andrp92 approved these changes

2021-06-14 17:27 UTC, andres-pcg commented on l10n_do_pos/models/pos_session.py
> +    def action_pos_session_close(self):
Copiado.!

2021-06-15 15:32 UTC, andrp92 commented
Con lo último que dijo @raulovallet , los escenarios quedan contemplados. 

@jlopezg plz review

2021-06-17 00:25 UTC, andrp92 commented
@akevinieron @jlopezg Review

2021-06-17 00:33 UTC, jlopezg commented on l10n_do_pos/i18n/es_DO.po
> +"del punto de venta o quite el check es fiscal? del Diario de ventas, solo el Diario de factura puede ser fiscal"
¿No hay un mensaje más conciso?

2021-06-17 02:26 UTC, raulovallet commented on l10n_do_pos/i18n/es_DO.po
> +"del punto de venta o quite el check es fiscal? del Diario de ventas, solo el Diario de factura puede ser fiscal"
cual recomiendas?

2021-06-17 19:30 UTC, jlopezg approved these changes

2021-06-17 19:30 UTC, jlopezg commented
@andrp92 @raulovallet ya.

2021-06-17 19:37 UTC, merged

2021-06-17 19:38 UTC, andrp92 commented
Thank you very much @raulovallet @jlopezg ❤️